lang: pt-BR

project:
  type: website
  output-dir: docs  # necessário para GitHub Pages

website:
  title: "Igor Espindola"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: Sobre
      - href: projetos.qmd
        text: Projetos
      - href: artigos.qmd
        text: Artigos
      - href: notebooks.qmd
        text: Notebooks
  page-footer:
    center: "© 2025 Igor Espindola · Contador & Fiscal de Tributos"

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
