lang: pt-BR

project:
  type: website
  output-dir: docs  # necessário para GitHub Pages

website:
  title: "Igor Espindola"
  favicon: imagens/LogoSemFundo.png
  navbar:
    logo: imagens/LogoSemFundo.png
    logo-alt: "Logo Igor Espindola"
    left:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: Sobre
      - href: projetos.qmd
        text: Projetos
      - href: servicos.qmd
        text: Serviços
      - href: pills.qmd
        text: Ideias
  page-footer:
    left: "© 2026 Igor Espindola"
    center: "Contador CRC-RJ 135764/O-4 · Fiscal de Tributos de Miracema/RJ"
    right:
      - icon: instagram
        href: https://www.instagram.com/idespindola

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-copy: true
    page-layout: full
